-- TalentQuest private audition video storage
-- Run this once in the Supabase SQL Editor.
-- Audition videos are private review material. Public contestant pages must not
-- use permanent public URLs for this bucket. Server-side/admin code should
-- generate short-lived signed URLs when an authorized reviewer needs playback.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'audition-videos',
  'audition-videos',
  false,
  209715200,
  array['video/mp4','video/quicktime','video/webm']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Step 1 only changes read privacy. Guest application uploads remain enabled
-- for now so the current application flow keeps working. Anonymous upload
-- hardening (CAPTCHA, rate limiting and server-authorized uploads) is Step 2.
drop policy if exists "Anyone can upload audition applications" on storage.objects;
create policy "Anyone can upload audition applications"
on storage.objects for insert
to anon, authenticated
with check (
  bucket_id = 'audition-videos'
  and (storage.foldername(name))[1] = 'applications'
);

-- Remove the old public-read policy. Private objects can instead be read via
-- short-lived signed URLs generated by trusted server-side code.
drop policy if exists "Public can view audition videos" on storage.objects;

-- Keep cleanup available for the existing browser application flow until Step 2
-- moves upload authorization and cleanup behind a server endpoint.
drop policy if exists "Applicants can remove failed audition uploads" on storage.objects;
create policy "Applicants can remove failed audition uploads"
on storage.objects for delete
to anon, authenticated
using (
  bucket_id = 'audition-videos'
  and (storage.foldername(name))[1] = 'applications'
);
