-- TalentQuest initial database schema
create extension if not exists pgcrypto;
create table if not exists public.applications (id uuid primary key default gen_random_uuid(),full_name text not null,stage_name text,email text not null,phone text not null,location text not null,category text not null,bio text not null,video_url text not null,instagram text,tiktok text,status text not null default 'pending' check(status in('pending','shortlisted','approved','rejected')),admin_notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.contestants (id uuid primary key default gen_random_uuid(),application_id uuid references public.applications(id) on delete set null,contestant_number text unique,full_name text not null,stage_name text,category text not null,bio text,photo_url text,video_url text,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.competition_rounds (id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,round_order integer not null,status text not null default 'draft' check(status in('draft','open','closed','completed')),public_vote_weight numeric not null default 60,judge_weight numeric not null default 40,starts_at timestamptz,ends_at timestamptz,created_at timestamptz not null default now());
alter table public.applications enable row level security;alter table public.contestants enable row level security;alter table public.competition_rounds enable row level security;
create policy "public can submit applications" on public.applications for insert to anon,authenticated with check(status='pending');
create policy "public can view active contestants" on public.contestants for select to anon,authenticated using(active=true);
create policy "public can view published rounds" on public.competition_rounds for select to anon,authenticated using(status<>'draft');
create index if not exists applications_status_idx on public.applications(status);create index if not exists applications_category_idx on public.applications(category);create index if not exists contestants_category_idx on public.contestants(category);
