import Link from "next/link";

const applications=[
 {name:"Amara Okafor",category:"Singing",city:"Abuja",status:"Pending",date:"Today"},
 {name:"David Eze",category:"Dance",city:"Lagos",status:"Shortlisted",date:"Today"},
 {name:"Zainab Musa",category:"Spoken Word",city:"Kaduna",status:"Pending",date:"Yesterday"},
 {name:"Tobi Adeyemi",category:"Comedy",city:"Ibadan",status:"Approved",date:"Yesterday"}
];
const stats=[["Applications","248","+32 this week"],["Approved talent","84","33.9% approval"],["Pending review","67","Needs attention"],["Published","52","Public profiles"]];
export default function AdminPage(){return <div className="adminShell"><aside className="adminSidebar"><Link href="/" className="brand"><span className="brandStar">★</span><span>Talent<b>Quest</b></span></Link><div className="adminLabel">MANAGEMENT</div><nav><a className="active">⌂ Dashboard</a><a>◫ Applications <b>67</b></a><a>★ Contestants</a><a>◈ Rounds</a><a>▤ Categories</a><div className="adminLabel">OPERATIONS</div><a>♛ Judges</a><a>◎ Voting</a><a>₦ Finance</a><a>▥ Reports</a><a>⚙ Settings</a></nav><div className="adminUser"><span>AD</span><div><b>Administrator</b><small>Super Admin</small></div></div></aside><main className="adminMain"><header className="adminTop"><div><span className="kicker">TALENTQUEST CONTROL ROOM</span><h1>Good afternoon, Admin.</h1><p>Here&apos;s what&apos;s happening across the competition.</p></div><Link href="/" className="button buttonGhost">View public site ↗</Link></header><section className="adminStats">{stats.map(([a,b,c])=><article key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></article>)}</section><section className="adminPanel"><div className="panelHead"><div><span className="kicker">APPLICATIONS</span><h2>Latest submissions</h2></div><Link href="/admin/applications">Review all →</Link></div><div className="adminTable"><div className="tableRow tableHeader"><span>Applicant</span><span>Category</span><span>Location</span><span>Status</span><span>Received</span><span></span></div>{applications.map((a)=><div className="tableRow" key={a.name}><span className="applicant"><i>{a.name.split(" ").map(x=>x[0]).join("")}</i><b>{a.name}</b></span><span>{a.category}</span><span>{a.city}</span><span><em className={`status ${a.status.toLowerCase()}`}>{a.status}</em></span><span>{a.date}</span><span>•••</span></div>)}</div></section><section className="adminBottom"><article className="adminPanel"><div className="panelHead"><div><span className="kicker">COMPETITION</span><h2>Season progress</h2></div></div><div className="roundLine"><b>Applications</b><span className="done">✓</span><b>Auditions</b><span>2</span><b>Top 50</b><span>3</span><b>Finale</b></div><p>Applications are currently open. Configure the next round when screening begins.</p></article><article className="adminPanel quick"><div className="panelHead"><div><span className="kicker">QUICK ACTIONS</span><h2>Manage</h2></div></div><Link href="/admin/applications">Review applications <span>→</span></Link><a>Add contestant <span>→</span></a><a>Create competition round <span>→</span></a><a>Manage talent categories <span>→</span></a></article></section></main></div>}
