"use client";
import Link from "next/link";
import {use,useEffect,useMemo,useState} from "react";
import {useSearchParams} from "next/navigation";
import {getSupabase} from "@/lib/supabase";
import "../vote.css";import "./vote-detail.css";

const PACKS=[1,5,10,25,50,100];
export default function VoteDetail({params}){const{id}=use(params),q=useSearchParams();const roundId=q.get("round");const[c,setC]=useState(null),[round,setRound]=useState(null),[qty,setQty]=useState(5),[email,setEmail]=useState(""),[name,setName]=useState("");useEffect(()=>{(async()=>{const s=getSupabase();const[{data:a},{data:r}]=await Promise.all([s.from("contestants").select("*").eq("id",id).eq("active",true).maybeSingle(),s.from("competition_rounds").select("*").eq("id",roundId).eq("status","live").eq("voting_enabled",true).maybeSingle()]);setC(a);setRound(r)})()},[id,roundId]);const total=useMemo(()=>round?round.vote_price_kobo*qty/100:0,[round,qty]);if(!c||!round)return <main className="votePage"><div className="container voteEmpty"><h2>Voting unavailable</h2><p>This contestant or voting round is not currently available.</p><Link href="/vote">← Return to voting</Link></div></main>;return <main className="voteCheckout"><div className="container"><Link href="/vote" className="voteBack">← Back to live voting</Link><div className="checkoutGrid"><section className="checkoutTalent"><div className="checkoutPhoto">{c.photo_url?<img src={c.photo_url} alt={c.stage_name||c.full_name}/>:<span>★</span>}<b>{c.contestant_number}</b></div><span className="kicker">YOU'RE SUPPORTING</span><h1>{c.stage_name||c.full_name}</h1><p>{c.category} • {round.name}</p></section><section className="ballot"><span className="kicker">CAST YOUR VOTE</span><h2>Choose your votes.</h2><p>Each verified vote directly adds to this contestant's total for {round.name}.</p><div className="packGrid">{PACKS.map(n=><button key={n} className={qty===n?"selected":""} onClick={()=>setQty(n)}><strong>{n}</strong><span>{n===1?"vote":"votes"}</span><small>₦{(n*round.vote_price_kobo/100).toLocaleString()}</small></button>)}</div><label>Your name <input value={name} onChange={e=>setName(e.target.value)} placeholder="Supporter name"/></label><label>Email address <input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><div className="ballotTotal"><span>Total</span><strong>₦{total.toLocaleString()}</strong></div><button className="payVote" disabled>Continue to secure payment →</button><small className="paymentNote">Payment activation is the next deployment step. No charge will be made yet.</small></section></div></div></main>}
