import {NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";

export const runtime="nodejs";
const PHOTO_TYPES=new Set(["image/jpeg","image/png","image/webp"]);
const VIDEO_TYPES=new Set(["video/mp4","video/quicktime","video/webm"]);
const MAX_PHOTO=5*1024*1024,MAX_VIDEO=200*1024*1024;
const WINDOW=10*60*1000,LIMIT=4;
const attempts=globalThis.__tqApplyRateLimit||(globalThis.__tqApplyRateLimit=new Map());
function json(message,status=400){return NextResponse.json({error:message},{status})}
function ipOf(req){return (req.headers.get("x-forwarded-for")||req.headers.get("x-real-ip")||"unknown").split(",")[0].trim()}
function limited(ip){const now=Date.now();const hits=(attempts.get(ip)||[]).filter(t=>now-t<WINDOW);hits.push(now);attempts.set(ip,hits);return hits.length>LIMIT}
function ext(file,fallback){const x=file.name?.split(".").pop()?.toLowerCase();return x&&/^[a-z0-9]{2,5}$/.test(x)?x:fallback}
async function verifyTurnstile(token,ip){const secret=process.env.TURNSTILE_SECRET_KEY;if(!secret)return process.env.NODE_ENV!=="production";const body=new URLSearchParams({secret,response:token||""});if(ip&&ip!=="unknown")body.set("remoteip",ip);const r=await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify",{method:"POST",body,cache:"no-store"});const data=await r.json();return !!data.success}
export async function POST(req){const ip=ipOf(req);if(limited(ip))return json("Too many application attempts. Please wait a few minutes and try again.",429);const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return json("Application service is not configured.",503);let fd;try{fd=await req.formData()}catch{return json("Invalid application data.")}
const token=String(fd.get("turnstileToken")||"");if(!(await verifyTurnstile(token,ip)))return json("Security check failed. Please complete the verification and try again.",403);
const photo=fd.get("photo"),video=fd.get("video");if(!(photo instanceof File)||!PHOTO_TYPES.has(photo.type)||photo.size>MAX_PHOTO)return json("Profile photo must be JPG, PNG or WebP and no larger than 5 MB.",415);if(!(video instanceof File)||!VIDEO_TYPES.has(video.type)||video.size>MAX_VIDEO)return json("Audition must be MP4, MOV or WebM and no larger than 200 MB.",415);
const required=["full_name","email","phone","location","category","bio"];const values={};for(const k of [...required,"stage_name","instagram","tiktok"]){values[k]=String(fd.get(k)||"").trim()}if(required.some(k=>!values[k]))return json("Please complete all required application fields.");if(values.bio.length>800)return json("Talent description must be 800 characters or fewer.");
const supabase=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const id=crypto.randomUUID(),photoPath=`applications/${id}.${ext(photo,"jpg")}`,videoPath=`applications/${id}.${ext(video,"mp4")}`;let uploadedPhoto=false,uploadedVideo=false;try{let up=await supabase.storage.from("contestant-photos").upload(photoPath,photo,{contentType:photo.type,upsert:false});if(up.error)throw up.error;uploadedPhoto=true;up=await supabase.storage.from("audition-videos").upload(videoPath,video,{contentType:video.type,upsert:false});if(up.error)throw up.error;uploadedVideo=true;const photo_url=supabase.storage.from("contestant-photos").getPublicUrl(photoPath).data.publicUrl;const auth=req.headers.get("authorization");let user_id=null;if(auth?.startsWith("Bearer ")){const{data}=await supabase.auth.getUser(auth.slice(7));user_id=data.user?.id||null}const{error}=await supabase.from("applications").insert({...values,photo_url,video_url:videoPath,user_id,status:"pending"});if(error)throw error;return NextResponse.json({ok:true,message:"Application submitted successfully. Your audition is now awaiting review."})}catch(e){if(uploadedPhoto)await supabase.storage.from("contestant-photos").remove([photoPath]);if(uploadedVideo)await supabase.storage.from("audition-videos").remove([videoPath]);console.error("application-submit",e);return json("We could not submit your application. Please try again.",500)}}
