"use client";
import { useState } from "react";
import { getSupabase } from "@/lib/supabase";

const categories=["Singing","Dance","Comedy","Acting","Spoken Word","Instrumental","Other"];
const initial={full_name:"",stage_name:"",email:"",phone:"",location:"",category:"Singing",bio:"",video_url:"",instagram:"",tiktok:""};
export default function ApplyPage(){
 const [form,setForm]=useState(initial); const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false); const change=e=>setForm({...form,[e.target.name]:e.target.value});
 async function submit(e){e.preventDefault();setBusy(true);setStatus("");const supabase=getSupabase();if(!supabase){setStatus("Applications are not connected yet. Add the Supabase environment variables to continue.");setBusy(false);return;}const {error}=await supabase.from("applications").insert({...form,status:"pending"});if(error)setStatus(error.message);else{setStatus("Application submitted successfully. Your TalentQuest journey starts here!");setForm(initial);}setBusy(false);}
 return <section className="formPage"><div className="container formWrap"><div className="formIntro"><span className="kicker">TALENTQUEST APPLICATIONS</span><h1>Your talent.<br/><em>Your stage.</em></h1><p>Tell us who you are and show us what you can do. Applications are reviewed before contestants advance to auditions.</p><div className="formNotes"><span>01 <b>Complete your profile</b></span><span>02 <b>Share an audition video</b></span><span>03 <b>Submit for review</b></span></div></div><form className="applicationForm" onSubmit={submit}><div className="formTitle"><span>★</span><div><h2>Contestant application</h2><p>Fields marked * are required.</p></div></div><div className="fields"><label>Full name *<input required name="full_name" value={form.full_name} onChange={change}/></label><label>Stage name<input name="stage_name" value={form.stage_name} onChange={change}/></label><label>Email address *<input required type="email" name="email" value={form.email} onChange={change}/></label><label>Phone number *<input required name="phone" value={form.phone} onChange={change}/></label><label>Location *<input required name="location" value={form.location} onChange={change}/></label><label>Talent category *<select name="category" value={form.category} onChange={change}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label className="fullField">Tell us about your talent *<textarea required rows="5" maxLength="800" name="bio" value={form.bio} onChange={change}/></label><label className="fullField">Audition video URL *<input required type="url" placeholder="YouTube, TikTok, Instagram or public video link" name="video_url" value={form.video_url} onChange={change}/><small>Use a public link the review team can open.</small></label><label>Instagram<input placeholder="@username" name="instagram" value={form.instagram} onChange={change}/></label><label>TikTok<input placeholder="@username" name="tiktok" value={form.tiktok} onChange={change}/></label></div><label className="consent"><input required type="checkbox"/><span>I confirm that my submission is accurate and I agree to the competition rules and media terms.</span></label>{status&&<div className="formStatus">{status}</div>}<button disabled={busy} className="button buttonGold submitButton">{busy?"Submitting...":"Submit application →"}</button></form></div></section>;
}
