"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {getSupabase} from "@/lib/supabase";
import "./home-show.css";

const talents=[["Singing","Voices that deserve a bigger room.","♪"],["Dance","Movement, rhythm and stage presence.","✦"],["Comedy","Original voices making audiences laugh.","☺"],["Acting","Performers built for screen and stage.","◈"],["Spoken Word","Stories, poetry and fearless expression.","❞"],["Instrumental","Musicianship you need to hear live.","♫"]];
export default function Home(){const[featured,setFeatured]=useState([]),[liveRound,setLiveRound]=useState(null);useEffect(()=>{(async()=>{const s=getSupabase();if(!s)return;const[{data:rounds},{data:people}]=await Promise.all([s.from("competition_rounds").select("id,name,voting_enabled,status").eq("status","live").order("created_at",{ascending:false}).limit(1),s.from("contestants").select("id,contestant_number,full_name,stage_name,category,bio,photo_url").eq("active",true).order("created_at",{ascending:false}).limit(3)]);setLiveRound(rounds?.[0]||null);setFeatured(people||[])})()},[]);return <main className="showHome"><section className="showHero"><div className="showNoise"/><div className="container showHeroInner"><div className="showHeroCopy"><div className="showSeason"><span>★</span><b>TALENTQUEST</b><i>{liveRound?`${liveRound.name} · LIVE NOW`:"THE SEARCH IS ON"}</i></div><h1>One stage.<br/><em>Unforgettable</em><br/>talent.</h1><p>Meet the performers worth talking about. Watch their journey, back your favourites and help decide who goes further.</p><div className="showHeroActions"><Link href="/contestants" className="button buttonGold">Meet the contestants →</Link>{liveRound?.voting_enabled?<Link href="/vote" className="showTextLink">Voting is live <span>●</span></Link>:<Link href="/apply" className="showTextLink">Enter TalentQuest →</Link>}</div></div><div className="showPoster"><div className="showPosterTop">{liveRound?<><span>NOW</span>{liveRound.name}</>:<>DISCOVER THE NEXT STAR</>}</div><div className="showPosterStar">★</div><div className="showPosterTitle">TALENT<br/><b>QUEST</b></div><div className="showPosterBottom"><span>DISCOVER</span><span>WATCH</span><span>VOTE</span></div></div></div><div className="container showTicker"><span>THE STAGE IS OPEN</span><p>Music · Dance · Comedy · Acting · Spoken Word · Instrumental</p><Link href="/apply">Think you belong here? Apply →</Link></div></section>
<section className="showFeatured"><div className="container"><div className="showSectionHead"><div><span className="kicker">IN THE SPOTLIGHT</span><h2>Meet the talent<br/><em>making noise.</em></h2></div><Link href="/contestants">View all contestants →</Link></div>{featured.length?<div className="showTalentRail">{featured.map((c,i)=><Link href={`/contestants/${c.id}`} className="showTalent" key={c.id}><div className="showTalentPhoto">{c.photo_url?<img src={c.photo_url} alt={c.stage_name||c.full_name}/>:<div className="showTalentFallback">★</div>}<span>0{i+1}</span></div><div className="showTalentCopy"><small>{c.category}</small><h3>{c.stage_name||c.full_name}</h3><p>{c.bio||"A TalentQuest contestant ready for the spotlight."}</p><b>{c.contestant_number} ↗</b></div></Link>)}</div>:<div className="showEmptyTalent"><span>★</span><h3>The next stars are getting ready.</h3><Link href="/apply">Apply for TalentQuest →</Link></div>}</div></section>
<section className="showLiveBand"><div className="container showLiveGrid"><div><span className="kicker">THE COMPETITION</span><h2>{liveRound?`${liveRound.name} is on.`:"Every round changes everything."}</h2></div><div><p>{liveRound?.voting_enabled?"Public voting is open. Every verified vote helps shape who moves closer to the final spotlight.":"Follow every audition, performance and elimination as the competition moves toward the grand finale."}</p><Link href={liveRound?.voting_enabled?"/vote":"/leaderboard"}>{liveRound?.voting_enabled?"Vote for your favourite":"See the leaderboard"} →</Link></div></div></section>
<section className="showCategories"><div className="container"><div className="showCategoryIntro"><span className="kicker">NO SINGLE KIND OF STAR</span><h2>Talent comes<br/>in many forms.</h2><p>We built one stage for performers who usually belong on very different ones.</p></div><div className="showCategoryList">{talents.map(([title,copy,icon],i)=><Link href="/contestants" key={title}><span>{String(i+1).padStart(2,"0")}</span><i>{icon}</i><strong>{title}</strong><p>{copy}</p><b>↗</b></Link>)}</div></div></section>
<section className="showFinal"><div className="container showFinalInner"><span className="kicker">YOUR TURN</span><h2>Don&apos;t just watch<br/>the next star.<br/><em>Be one.</em></h2><p>If you can sing, dance, act, make people laugh, move a room with words or own an instrument, we want to see it.</p><Link href="/apply" className="button buttonGold">Start your application →</Link></div></section></main>}
